kind: RestDefinition
apiVersion: ogen.krateo.io/v1alpha1
metadata:
  name: mlflow-experiments
  namespace: default
spec:
  
  oasPath: https://raw.githubusercontent.com/krateoplatformops/mlflow-oas3/main/mlflow.yaml
  resourceGroup: local.mlflow.com
  resource: 
    kind: Experiment
    identifiers:
      - experiment_id # This is the field that will be used as the identifier
    verbsDescription:
    - action: create
      method: POST
      path: /api/2.0/mlflow/experiments/create
    - action: delete
      method: POST
      path: /api/2.0/mlflow/experiments/delete
    - action: get
      method: GET
      path: /api/2.0/mlflow/experiments/get
    - action: update
      method: POST
      path: /api/2.0/mlflow/experiments/update