kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-github-collaborators
  namespace: default
spec:
   
  oasPath: https://raw.githubusercontent.com/krateoplatformops/github-oas3/c25b1c98e9b13efa4a7d1a9b387facc5df963bf8/openapi-webservice.yaml
  resourceGroup: gen.github.com
  resource: 
    kind: Collaborators
    identifiers:
      - id 
      - permissions
      - html_url
    verbsDescription:
    - action: create
      method: PUT
      path: /repos/{owner}/{repo}/collaborators/{username}
    - action: delete
      method: DELETE
      path: /repos/{owner}/{repo}/collaborators/{username}
    - action: get
      method: GET
      path: /repository/{owner}/{repo}/collaborators/{username}/permission
    - action: update
      method: PUT
      path: /repos/{owner}/{repo}/collaborators/{username}
