apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasgen-provider-dev
  namespace: demo-system
  labels:
    app.kubernetes.io/name: oasgen-provider-dev
    app: oasgen-provider-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oasgen-provider-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oasgen-provider-dev
        app: oasgen-provider-dev
    spec:
      serviceAccountName: oasgen-provider-dev
      containers:
      - name: oasgen-provider-dev-container
        image: kind.local/oasgen-provider:latest
        imagePullPolicy: Never
        args:
          - --debug
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp/assets/rdc-deployment
          name: rdc-deployment
          readOnly: true
        - mountPath: /tmp/assets/rdc-configmap
          name: rdc-configmap
          readOnly: true
        - mountPath: /tmp/assets/rdc-rbac
          name: rdc-rbac
          readOnly: true
      volumes:
      - name: rdc-deployment
        configMap:
          name: rdc-deployment
      - name: rdc-configmap
        configMap:
          name: rdc-configmap
      - name: rdc-rbac
        configMap:
          name: rdc-rbac-configmap