//go:build !ignore_autogenerated

/*
Copyright 2025 Krateo SRL.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationField) DeepCopyInto(out *ConfigurationField) {
	*out = *in
	out.FromOpenAPI = in.FromOpenAPI
	out.FromRestDefinition = in.FromRestDefinition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationField.
func (in *ConfigurationField) DeepCopy() *ConfigurationField {
	if in == nil {
		return nil
	}
	out := new(ConfigurationField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromOpenAPI) DeepCopyInto(out *FromOpenAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromOpenAPI.
func (in *FromOpenAPI) DeepCopy() *FromOpenAPI {
	if in == nil {
		return nil
	}
	out := new(FromOpenAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromRestDefinition) DeepCopyInto(out *FromRestDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromRestDefinition.
func (in *FromRestDefinition) DeepCopy() *FromRestDefinition {
	if in == nil {
		return nil
	}
	out := new(FromRestDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindApiVersion) DeepCopyInto(out *KindApiVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindApiVersion.
func (in *KindApiVersion) DeepCopy() *KindApiVersion {
	if in == nil {
		return nil
	}
	out := new(KindApiVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	if in.VerbsDescription != nil {
		in, out := &in.VerbsDescription, &out.VerbsDescription
		*out = make([]VerbsDescription, len(*in))
		copy(*out, *in)
	}
	if in.Identifiers != nil {
		in, out := &in.Identifiers, &out.Identifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalStatusFields != nil {
		in, out := &in.AdditionalStatusFields, &out.AdditionalStatusFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigurationFields != nil {
		in, out := &in.ConfigurationFields, &out.ConfigurationFields
		*out = make([]ConfigurationField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinition) DeepCopyInto(out *RestDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinition.
func (in *RestDefinition) DeepCopy() *RestDefinition {
	if in == nil {
		return nil
	}
	out := new(RestDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinitionList) DeepCopyInto(out *RestDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinitionList.
func (in *RestDefinitionList) DeepCopy() *RestDefinitionList {
	if in == nil {
		return nil
	}
	out := new(RestDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinitionSpec) DeepCopyInto(out *RestDefinitionSpec) {
	*out = *in
	in.Resource.DeepCopyInto(&out.Resource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinitionSpec.
func (in *RestDefinitionSpec) DeepCopy() *RestDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(RestDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinitionStatus) DeepCopyInto(out *RestDefinitionStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.Resource = in.Resource
	out.Configuration = in.Configuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinitionStatus.
func (in *RestDefinitionStatus) DeepCopy() *RestDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(RestDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerbsDescription) DeepCopyInto(out *VerbsDescription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerbsDescription.
func (in *VerbsDescription) DeepCopy() *VerbsDescription {
	if in == nil {
		return nil
	}
	out := new(VerbsDescription)
	in.DeepCopyInto(out)
	return out
}
