kind: RestDefinition
apiVersion: ogen.krateo.io/v1alpha1
metadata:
  name: def-pipelinepermissions
  namespace: default
spec:
  
  oasPath: https://raw.githubusercontent.com/krateoplatformops/azuredevops-oas3/refs/heads/1-webservices/approvalandchecks/pipelinepermissions.yaml
  resourceGroup: azure.devops.com
  resource: 
    kind: PipelinePermission
    identifiers:
      - resourceType
      - resourceId
    verbsDescription:
    - action: findby
      method: POST
      path: /ws/{organization}/{project}/_apis/pipelines/pipelinepermissions/{resourceType}/{resourceId}
    - action: get
      method: POST
      path: /ws/{organization}/{project}/_apis/pipelines/pipelinepermissions/{resourceType}/{resourceId}
    - action: update
      method: PATCH
      path: /{organization}/{project}/_apis/pipelines/pipelinepermissions/{resourceType}/{resourceId}
    - action: create
      method: PATCH
      path: /{organization}/{project}/_apis/pipelines/pipelinepermissions/{resourceType}/{resourceId}


  