apiVersion: v1
kind: ConfigMap
metadata:
  name: rdc-rbac-configmap
  namespace: demo-system
data:
  serviceaccount.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ .resource }}-{{ .apiVersion }}
      namespace: {{ .namespace }}
  clusterrole.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: {{ .resource }}-{{ .apiVersion }}
    rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "list"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch", "update"]
    - apiGroups: ["ogen.krateo.io"]
      resources: ["restdefinitions", "restdefinitions/status"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [ {{ .apiGroup }}]
      resources: ["{{ .resource }}", "{{ .resource }}/status"]
      verbs: ["*"]
    {{- if .configuration }}
    - apiGroups: [{{ .apiGroup }}]
      resources:
      - "{{ .configuration }}"
      verbs: ["*"]
    {{- end }}
  clusterrolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: {{ .resource }}-{{ .apiVersion }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: {{ .resource }}-{{ .apiVersion }}
    subjects:
    - kind: ServiceAccount
      name: {{ .serviceAccount }}
      namespace: {{ .namespace }}
  role.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: {{ .resource }}-{{ .apiVersion }}
      namespace: {{ .namespace }}
    rules:
  rolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: {{ .resource }}-{{ .apiVersion }}
      namespace: {{ .namespace }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: {{ .resource }}-{{ .apiVersion }}
    subjects:
    - kind: ServiceAccount
      name: {{ .serviceAccount }}
      namespace: {{ .namespace }}

  